name: Release → Discord

on:
  release:
    types: [published, edited]  # fire on publish and edit

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      # New release published (skip prereleases)
      - name: Post NEW release to Discord
        if: github.event.action == 'published' && !github.event.release.prerelease
        uses: SethCohen/github-releases-to-discord@v1.15.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Release Bot"
          # This shows above the embed. The action auto-builds a nice embed from the release.
          content: "🎉 **New release:** ${{ github.event.release.tag_name }}"

      # Release edited (skip prereleases)
      - name: Post UPDATED release to Discord
        if: github.event.action == 'edited' && !github.event.release.prerelease
        uses: SethCohen/github-releases-to-discord@v1.15.1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          username: "Release Bot"
          content: "✏️ **Release updated:** ${{ github.event.release.tag_name }}"

      # ——— OPTIONAL: include prereleases too ———
      # Uncomment to announce prereleases (or send these to a different webhook/channel).
      # - name: Pre-release published
      #   if: github.event.action == 'published' && github.event.release.prerelease
      #   uses: SethCohen/github-releases-to-discord@v1.15.1
      #   with:
      #     webhook: ${{ secrets.DISCORD_WEBHOOK_PRERELEASE }}
      #     username: "Release Bot"
      #     content: "🧪 **Pre-release:** ${{ github.event.release.tag_name }}"
